#!/usr/bin/env python3
"""
Fix SVG files generated by the Python diagrams library.
Converts external PNG icon references to embedded base64 data URIs.
"""

import base64
import os
import re
import sys
from pathlib import Path


def get_base64_data_uri(png_path: str) -> str | None:
    """Convert a PNG file to a base64 data URI."""
    if os.path.exists(png_path):
        with open(png_path, "rb") as f:
            data = base64.b64encode(f.read()).decode("utf-8")
            return f"data:image/png;base64,{data}"
    return None


def fix_svg_file(svg_path: str, dry_run: bool = False) -> tuple[int, int]:
    """
    Fix a single SVG file by embedding PNG icons as base64.

    Returns: (total_refs, fixed_refs)
    """
    with open(svg_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Find all xlink:href references to PNG files
    pattern = r'xlink:href="([^"]+\.png)"'
    matches = list(re.finditer(pattern, content))

    if not matches:
        return (0, 0)

    total_refs = len(matches)
    fixed_refs = 0
    new_content = content

    # Process each match (reverse order to preserve positions)
    for match in reversed(matches):
        png_path = match.group(1)
        data_uri = get_base64_data_uri(png_path)

        if data_uri:
            old_ref = f'xlink:href="{png_path}"'
            new_ref = f'xlink:href="{data_uri}"'
            new_content = new_content[:match.start()] + new_ref + new_content[match.end():]
            fixed_refs += 1

    if not dry_run and fixed_refs > 0:
        with open(svg_path, "w", encoding="utf-8") as f:
            f.write(new_content)

    return (total_refs, fixed_refs)


def main():
    # Find all SVG files with PNG references
    docs_images = Path("/workspaces/sov-cloud-brain-trek/docs/assets/images")

    svg_files = list(docs_images.rglob("*.svg"))

    print(f"Scanning {len(svg_files)} SVG files...")
    print("-" * 60)

    total_files = 0
    total_refs = 0
    total_fixed = 0

    for svg_file in sorted(svg_files):
        refs, fixed = fix_svg_file(str(svg_file), dry_run=False)
        if refs > 0:
            status = "✅" if fixed == refs else ("⚠️" if fixed > 0 else "❌")
            rel_path = svg_file.relative_to(docs_images)
            print(f"{status} {rel_path}: {fixed}/{refs} icons embedded")
            total_files += 1
            total_refs += refs
            total_fixed += fixed

    print("-" * 60)
    print(f"Summary: {total_fixed}/{total_refs} icons embedded across {total_files} files")

    if total_fixed < total_refs:
        missing = total_refs - total_fixed
        print(f"⚠️  {missing} icons could not be found and were NOT embedded")
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
